In [1]:
## Numpy

Импортировать NumPy под именем np

In [2]:
import numpy as np  

Создать вектор (одномерный массив) размера 10, заполненный нулями

In [3]:
zeros = np.zeros(10)

Создать вектор размера 10, заполненный единицами

In [6]:
ones = np.ones(10)

Создать вектор размера 10, заполненный числом 2.5

In [8]:
arr_2_5 = np.ones(10) * 2.5

Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [10]:
arr_0_1 = np.zeros(10)
arr_0_1[4] = 1
print(arr_0_1)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


Развернуть вектор (первый становится последним)

In [11]:
v = np.arange(10)
print(v[::-1])

[9 8 7 6 5 4 3 2 1 0]


Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [12]:
m = np.arange(9).reshape((3,3))
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [14]:
arr = [1,2,0,0,4,0]
print(np.nonzero(arr))

(array([0, 1, 4], dtype=int64),)


Создать 3x3 единичную матрицу

In [15]:
print(np.ones((3,3)))

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Создать массив 3x3x3 со случайными значениями

In [16]:
print(np.random.random((3,3,3)))

[[[ 0.05291446  0.50290663  0.80036424]
  [ 0.12125968  0.10811646  0.4402556 ]
  [ 0.6464682   0.35573254  0.34159737]]

 [[ 0.12317795  0.7220338   0.64850992]
  [ 0.15703045  0.97488651  0.43157921]
  [ 0.65337262  0.18340062  0.33072625]]

 [[ 0.86830231  0.16574906  0.31098097]
  [ 0.97816345  0.75208798  0.71138423]
  [ 0.84447702  0.67622769  0.16006096]]]


Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [22]:
arr = np.random.random(30)
print(arr.mean())

0.479932157139


Перемножить матрицы 5x3 и 3x2

In [44]:
m1 = np.matrix(np.random.random((5,3)))
m2 = np.matrix((np.random.random((3,2))))
print(m1 * m2)

[[ 1.23590838  0.07598143]
 [ 0.51153753  0.05147008]
 [ 0.98217844  0.08626763]
 [ 1.47858654  0.11067652]
 [ 0.49401952  0.06196259]]


Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [45]:
print(np.random.random(10))

[ 0.36498218  0.8715001   0.71648888  0.24915806  0.03638813  0.44588685
  0.16222269  0.61416405  0.85809676  0.24315025]


Заменить максимальный элемент на ноль

In [47]:
arr = np.arange(10)
arr[arr.argmax()] = 0
print(arr)

[0 1 2 3 4 5 6 7 8 0]


Преобразовать массив из float в int

In [49]:
f_arr = np.random.random(10)
print(f_arr.astype(int))

[0 0 0 0 0 0 0 0 0 0]


Дан массив (10,2) координат, найти расстояние от каждой точки до каждой

In [53]:
cords = np.random.random(20).reshape((10,2))
print(cords)
distance = np.sum((cords[:,np.newaxis,:] - cords[np.newaxis,:,:]) ** 2, axis=-1)
print(distance)

[[ 0.77267978  0.50673203]
 [ 0.82784538  0.53837262]
 [ 0.97811735  0.83834364]
 [ 0.51308044  0.3142009 ]
 [ 0.33453078  0.06723931]
 [ 0.85001552  0.29197102]
 [ 0.25397554  0.04508832]
 [ 0.17638278  0.01879239]
 [ 0.2488276   0.34975813]
 [ 0.14233787  0.46256626]]
Wall time: 0 ns
[[ 0.          0.00404437  0.15217085  0.10446005  0.3851284   0.05210311
   0.48216901  0.5936552   0.29906191  0.39928153]
 [ 0.00404437  0.          0.11256428  0.14932993  0.46532589  0.06120526
   0.572656    0.69436713  0.37083702  0.47566715]
 [ 0.15217085  0.11256428  0.          0.49098494  1.00880556  0.31493312
   1.15363537  1.31444257  0.77057935  0.83973598]
 [ 0.10446005  0.14932993  0.49098494  0.          0.09287001  0.11401941
   0.13955693  0.2006315   0.07109388  0.15946233]
 [ 0.3851284   0.46532589  1.00880556  0.09287001  0.          0.31622886
   0.00697981  0.02735789  0.08716192  0.19322151]
 [ 0.05210311  0.06120526  0.31493312  0.11401941  0.31622886  0.
   0.41621473  0.52840

Случайно расположить p элементов в 2D массив

In [59]:
arr2d = np.random.random(10).reshape((5,2))
print(arr2d)
arr_p = np.ones(4)
print(arr_p)
np.put(arr2d, np.random.choice(np.arange(5 * 2), 4, replace=False), arr_p)
print(arr2d)

[[ 0.9397343   0.12988743]
 [ 0.35873832  0.63155465]
 [ 0.21000588  0.38439097]
 [ 0.32966285  0.5457303 ]
 [ 0.95393601  0.63642292]]
[ 1.  1.  1.  1.]
[[ 0.9397343   0.12988743]
 [ 1.          1.        ]
 [ 1.          0.38439097]
 [ 0.32966285  1.        ]
 [ 0.95393601  0.63642292]]


Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [60]:
v = np.array([1, 2, 3, 4, 5])
print(np.append(v[:, np.newaxis], np.zeros((len(v), 3), dtype=int), axis=1).ravel())

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


Найти наиболее частое значение в массиве

In [62]:
arr = np.array([0,1,1,1,2,3,4,5,5])
counts = np.bincount(arr)
print(arr[np.argmax(counts)])

1


Найти n наибольших значений в массиве

In [66]:
n = 4
arr = np.random.random(20)
print(arr[arr.argsort()[n * -1:]])

[ 0.83865427  0.89045858  0.8951481   0.986707  ]


## Pandas - изучение данных

Перейти по ссылке [Kaggle]( https://www.kaggle.com/openfoodfacts/world-food-facts)

Скачать датасет на свой компьютер и распаковать

Считать csv файл в датафрейм food

In [71]:
import pandas as pd
food = pd.read_csv('en.openfoodfacts.org.products.tsv', sep='\t', low_memory=False)

Посмотреть первые 5 записей

In [74]:
print(food.iloc[:5])

            code                                                url  \
0  0000000003087  http://world-en.openfoodfacts.org/product/0000...   
1  0000000004530  http://world-en.openfoodfacts.org/product/0000...   
2  0000000004559  http://world-en.openfoodfacts.org/product/0000...   
3  0000000016087  http://world-en.openfoodfacts.org/product/0000...   
4  0000000016094  http://world-en.openfoodfacts.org/product/0000...   

                      creator   created_t      created_datetime  \
0  openfoodfacts-contributors  1474103866  2016-09-17T09:17:46Z   
1             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
2             usda-ndb-import  1489069957  2017-03-09T14:32:37Z   
3             usda-ndb-import  1489055731  2017-03-09T10:35:31Z   
4             usda-ndb-import  1489055653  2017-03-09T10:34:13Z   

  last_modified_t last_modified_datetime                    product_name  \
0      1474103893   2016-09-17T09:18:13Z              Farine de blé noir   
1      1489069957 

Сколько наблюдений в наборе данных?


In [75]:
print(len(food))

356027


Сколько столбцов в наборе данных?

In [76]:
print(len(food.columns))

163


Напечатайте все названия столбцов

In [77]:
print(food.columns)

Index([u'code', u'url', u'creator', u'created_t', u'created_datetime',
       u'last_modified_t', u'last_modified_datetime', u'product_name',
       u'generic_name', u'quantity',
       ...
       u'fruits-vegetables-nuts_100g', u'fruits-vegetables-nuts-estimate_100g',
       u'collagen-meat-protein-ratio_100g', u'cocoa_100g', u'chlorophyl_100g',
       u'carbon-footprint_100g', u'nutrition-score-fr_100g',
       u'nutrition-score-uk_100g', u'glycemic-index_100g',
       u'water-hardness_100g'],
      dtype='object', length=163)


Какое название у 105 столбца?

In [79]:
print(food.columns[104])

-glucose_100g


Какой тип наблюдений в 105 столбце?

In [82]:
print(food.iloc[:, 105].dtype)

float64


Как проиндексирован набор данных?

In [85]:
print(food.index)

RangeIndex(start=0, stop=356027, step=1)


Каково значение имени продукта в 19-м наблюдении?

In [84]:
print(food['product_name'][19])

Organic Oat Groats


## Pandas - фильтрация данных

Считать данные по  [адресу](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv). 
Присвоить переменной chipo

In [86]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t', low_memory=False)

Как много продуктов стоят более чем $10.00?

In [114]:
print(len(chipo['item_price'][chipo['item_price'].replace('[\$]', '', regex=True).astype(float) > 10.]))

1130


Какова цена каждого предмета? Напечатать столбцы item_name и item_price

In [88]:
print(chipo[['item_name', 'item_price']])

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39 
1                                      Izze     $3.39 
2                          Nantucket Nectar     $3.39 
3     Chips and Tomatillo-Green Chili Salsa     $2.39 
4                              Chicken Bowl    $16.98 
5                              Chicken Bowl    $10.98 
6                             Side of Chips     $1.69 
7                             Steak Burrito    $11.75 
8                          Steak Soft Tacos     $9.25 
9                             Steak Burrito     $9.25 
10                      Chips and Guacamole     $4.45 
11                     Chicken Crispy Tacos     $8.75 
12                       Chicken Soft Tacos     $8.75 
13                             Chicken Bowl    $11.25 
14                      Chips and Guacamole     $4.45 
15    Chips and Tomatillo-Green Chili Salsa     $2.39 
16                          Chicken Burrito     $8.49 
17        

Отсортировать по имени предмета

In [105]:
print(chipo.sort_values(by=['item_name']))

      order_id  quantity          item_name  \
3389      1360         2  6 Pack Soft Drink   
341        148         1  6 Pack Soft Drink   
1849       749         1  6 Pack Soft Drink   
1860       754         1  6 Pack Soft Drink   
2713      1076         1  6 Pack Soft Drink   
3422      1373         1  6 Pack Soft Drink   
553        230         1  6 Pack Soft Drink   
1916       774         1  6 Pack Soft Drink   
1922       776         1  6 Pack Soft Drink   
1937       784         1  6 Pack Soft Drink   
3836      1537         1  6 Pack Soft Drink   
298        129         1  6 Pack Soft Drink   
1976       798         1  6 Pack Soft Drink   
1167       481         1  6 Pack Soft Drink   
3875      1554         1  6 Pack Soft Drink   
1124       465         1  6 Pack Soft Drink   
3886      1558         1  6 Pack Soft Drink   
2108       849         1  6 Pack Soft Drink   
3010      1196         1  6 Pack Soft Drink   
4535      1803         1  6 Pack Soft Drink   
4169      166

Сколько было заказано самого дорогого предмета?

In [125]:
most_exp_idx = chipo['item_price'].replace('[\$]', '', regex=True).astype(float).argmax()
most_exp_name = chipo['item_name'][most_exp_idx]
print(chipo['quantity'][chipo['item_name'] == most_exp_name].sum())

130


Сколько раз был заказан предмет "Veggie Salad Bowl"?

In [115]:
print(len(chipo[chipo['item_name'] == 'Veggie Salad Bowl']))

18


Сколько раз люди заказали более чем 1 предмет "Canned Soda"?

In [120]:
print(len(chipo[(chipo['item_name'] == 'Canned Soda') & (chipo['quantity'] > 1)]))

20
